language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements_no_pdf.txt"
  - "pip install python-coveralls pytest-cov"
  - "python setup.py install"
script: py.test tests/ --doctest-modules  -v --cov bin --cov data_deletion --cov project_report--cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
