language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
  - "pip install coverage --upgrade"
script: py.test tests/ -v --cov bin --cov data_deletion --cov project_report --cov upload_to_gel --cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
