language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get install libffi-dev
install: "pip install -r requirements.txt"
script: py.test
# branches:
#   only:
#     - master
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
